export const ACCOUNT_ACCESS = 'ACCOUNT_ACCESS';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const GET_GAS_PRICE = 'GET_GAS_PRICE';
export const GET_ETH_PRICE = 'GET_ETH_PRICE';
export const GET_ETH_BALANCE = 'GET_ETH_BALANCE';
export const GET_NONCE = 'GET_NONCE';

export const SPIN_REFRESH_ICON_ETH = 'SPIN_REFRESH_ICON_ETH';
export const SPIN_REFRESH_ICON_TOKENS = 'SPIN_REFRESH_ICON_TOKENS';

export const CHANGE_NETWORK = 'CHANGE_NETWORK';

export const ADD_TOKEN = 'ADD_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const REFRESH_TOKEN_BALANCE = 'REFRESH_TOKEN_BALANCE';

export const TOKEN_ERROR = 'TOKEN_ERROR';
export const TOKEN_ERROR_HIDE = 'TOKEN_ERROR_HIDE';

export const GAS_SETTINGS = 'GAS_SETTINGS';

export const GET_TX_HASH = 'GET_TX_HASH';
export const TX_LOADING = 'TX_LOADING';
export const CLEAR_TX_DATA = 'CLEAR_TX_DATA';